salesforce/day11/source/force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/day11/source/force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce/day11/source/force-app/main/default/classes/StatisticsService.cls
public class StatisticsService {

    public static void updateStatistics(
        List<Application__c> newApplications,
        Map<Id,Application__c> oldMap
    ){

        for(Application__c app : newApplications){

            Application__c oldApp = oldMap.get(app.Id);

            if(oldApp.Status__c != 'Selected' &&
               app.Status__c == 'Selected'){

                System.debug('Placement Statistics Updated');

            }

        }

    }

}